version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: always
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
      image: mher/flower
      env_file:
        - ./.env
      ports:
        - "8888:8888"
      depends_on:
        - rabbitmq
